### ISSUE TITLE
Create tests for all views in API

### ISSUE THREAD

**Issue by Sourc** [mvk-tft/backend#22]
Create tests for the following views:
- [x] Truck
- [x] Shipment
- [x] Company
- [x] Cargo

At least the following should be tested:
- Create, update, delete & retrieve with / without permission
- 1000+ requests at once
- Interactions between different models

**Comment by arnte01** [comment]
Jag börjar på Company tester

**Comment by daniel-ty** [comment]
Jag gör Truck tester

**Comment by lucianozapata** [comment]
marcus och jag fixar Shipment och Cargo
